insert into procedures (name, description, price, category_ID)
VALUES ('Blood tests', 'A test done on a sample of blood to measure the amount of certain substances in the blood or to count different types of blood cells. Blood tests may be done to look for signs of disease or agents that cause disease, to check for antibodies or tumor markers, or to see how well treatments are working.',
        468.65, 1),
    ('Imaging study', 'A type of test that makes detailed pictures of areas inside the body. Imaging tests use different forms of energy, such as x-rays (high-energy radiation), ultrasound (high-energy sound waves), radio waves, and radioactive substances.',
     511.61, 1),
    ('Biopsies', 'A biopsy is a procedure to remove cells, tissue or fluid for examination by a medical pathologist. Healthcare providers do biopsies when they identify areas of concern or if you have symptoms or signs of certain conditions. There are different types of biopsy procedures.',
     2046.12, 1),
    ('Endoscopy', 'An endoscopy is a test to look inside your body. A long, thin tube with a small camera inside, called an endoscope, is passed into your body through a natural opening such as your mouth. Your GP may refer you for an endoscopy if you\'re having certain symptoms. It will usually be done at an endoscopy unit in a hospital.',
     200.00, 1),
    ('Electrocardiogram', 'An electrocardiogram (ECG or EKG) is a quick test to check the heartbeat. It records the electrical signals in the heart. Test results can help diagnose heart attacks and irregular heartbeats, called arrhythmias. ECG machines can be found in medical offices, hospitals, operating rooms and ambulances.',
     220.98, 1),
    ('Genetic testing', 'Genetic testing involves examining a person\'s blood or other tissues to determine whether he or she has a change in his or her genetic material. Genetic testing may be useful in determining whether an individual has a genetic condition or may develop one in the future.',
     1399.99, 1),
    ('Medication administration', 'Medication administration: the direct application of a prescribed medication—whether by injection, inhalation, ingestion, or other means—to the body of the individual by an individual legally authorized to do so.',
     388.00, 2),
    ('Radiation therapy', 'Radiation therapy (also called radiotherapy) is a cancer treatment that uses high doses of radiation to kill cancer cells and shrink tumors. At low doses, radiation is used in x-rays to see inside your body, as with x-rays of your teeth or broken bones.',
     672.82, 2),
    ('Physical therapy', 'Physical therapy (PT) is a healthcare specialty focused on the evaluation, treatment, and prevention of physical impairments, disabilities, and pain through non-invasive techniques. It aims to improve or restore mobility, function, and quality of life.',
     260.50, 2),
    ('Chemotherapy', 'Chemotherapy is a drug treatment that uses powerful chemicals to kill fast-growing cells in your body. Chemotherapy is most often used to treat cancer, since cancer cells grow and multiply much more quickly than most cells in the body.',
     8000.00, 2),
    ('Immunotherapy', 'A type of therapy that uses substances to stimulate or suppress the immune system to help the body fight cancer, infection, and other diseases. Some types of immunotherapy only target certain cells of the immune system.',
     1299.00, 2),
    ('General surgery', '"General Surgery" is a discipline of surgery having a central core of knowledge embracing anatomy, physiology, metabolism, immunology, nutrition, pathology, wound healing, shock and resuscitation, intensive care, and neoplasia, which are common to all surgical specialties.',
     699.99, 3),
    ('Cardiovascular surgery', 'Cardiovascular surgery, also referred to as cardiac surgery or heart surgery, describes any surgical procedure that involves the heart, or the blood vessels that carry blood to and from the heart.',
     768.65, 3),
    ('Orthopedic surgery', 'Orthopaedic surgery is a procedure on your musculoskeletal system. It can diagnose, treat, repair and prevent conditions that affect your bones, muscles and joints. Common types of orthopaedic surgery are ACL surgery and knee replacement surgery.',
     7600.00, 3),
    ('Neurosurgery', 'Neurosurgery is a surgical specialty that involves the conservative and surgical management of a wide variety of disorders affecting the brain, the spinal cord and spinal column, and the peripheral nerves.',
     2192.15, 3),
    ('Laparoscopy', 'Laparoscopy is a surgical procedure used to examine the organs in the belly (abdomen). It can also examine a woman''s pelvic organs. Laparoscopy uses a thin lighted tube that has a video camera. The tube is called a laparoscope.',
     25695.03, 4),
    ('Arthroscopy', 'Arthroscopy (ahr-THROS-kuh-pee) is a procedure for diagnosing and treating joint problems. A surgeon inserts a narrow tube attached to a fiber-optic video camera through a small incision — about the size of a buttonhole. The view inside your joint is transmitted to a high-definition video monitor.',
     21651.81, 4),
    ('Angioplasty and stent placement', 'Angioplasty is a procedure to open narrowed or blocked blood vessels that supply blood to the heart. These blood vessels are called the coronary arteries. A coronary artery stent is a small, metal mesh tube that expands inside a coronary artery. A stent is often placed during or immediately after angioplasty.',
     22572.76, 4),
    ('Endoscopic surgery', 'During endoscopic surgery an endoscope, which is an optical instrument in the form of a tube with a light source and a video camera at its tip, is introduced inside the body via the rectum or through an incision, thereby allowing the surgeon to observe the organ or area to be treated on a monitor.',
     2016.00, 4),
    ('Cardiopulmonary resuscitation (CPR)', 'Cardiopulmonary resuscitation (CPR) combines rescue breathing (mouth-to-mouth) and chest compressions to temporarily pump enough blood to the brain until specialised treatment is available. Chest compressions are the priority in CPR.',
     46901.54, 5),
    ('Tracheostomy', 'Tracheostomy (tray-key-OS-tuh-me) is a hole that surgeons make through the front of the neck and into the windpipe (trachea). A tracheostomy tube is placed into the hole to keep it open for breathing. The term for the surgical procedure to create this opening is tracheotomy.',
     1812.23, 5),
    ('Emergency surgery', 'Emergency Surgery can be defined as surgery that is required to deal with an acute threat to life, organ, limb or tissue caused by external trauma, acute disease process, acute exacerbation of a chronic disease process, or complication of a surgical or other interventional procedure.',
     695679.61, 5),
    ('Intubation and mechanical ventilation', 'Intubation places a tube in the throat to help move air in and out of the lungs. Mechanical ventilation is the use of a machine to move the air in and out of the lungs.',
     164098.54, 5),
    ('Cesarean section', 'Cesarean section is a fetal delivery through an open abdominal incision (laparotomy) and an incision in the uterus (hysterotomy). The first cesarean documented occurred in 1020 AD, and since then, the procedure has evolved tremendously.',
     146939.81, 6),
    ('Hysterectomy', 'A hysterectomy is the surgical removal of your uterus and, most likely, your cervix. Depending on the reason for the surgery, a hysterectomy may involve removing surrounding organs and tissues, like your fallopian tubes and ovaries.',
     61383.50, 6),
    ('In vitro fertilization', 'A procedure in which eggs are removed from a woman\'s ovary and combined with sperm outside the body to form embryos. The embryos are grown in the laboratory for several days and then either placed in a woman''s uterus or cryopreserved (frozen) for future use. Also called IVF.',
     18000.00, 6),
    ('Prenatal testing', 'Prenatal screening tests can identify whether your baby is more or less likely to have certain birth defects, many of which are genetic disorders. These tests include blood tests, a specific type of ultrasound and prenatal cell-free DNA screening.',
     2990.00, 6),
    ('Pelvic exams and Pap smears', 'A pelvic exam often lasts only a few minutes. Your doctor or other care provider checks your vulva, vagina, cervix, ovaries, uterus, rectum and pelvis for any unusual changes. A Pap test, which screens for cervical cancer, is often done during a pelvic exam.',
     818.45, 6),
    ('Vaccinations', 'Vaccination is a simple, safe, and effective way of protecting you against harmful diseases, before you come into contact with them. It uses your body’s natural defenses to build resistance to specific infections and makes your immune system stronger.',
     100.00, 7),
    ('Screening', 'A test or examination to discover if there is anything wrong with someone.',
     8941.53, 7),
    ('Health check-up', 'An occasion when a doctor or nurse examines someone\'s body, takes blood tests, etc. in order to make sure the person has no health problems',
     3726.48, 7),
    ('Lifestyle counseling', 'Lifestyle counseling is a holistic approach that focuses on helping individuals make positive changes to their daily habits and behaviors to improve overall health and well-being. It involves providing guidance and support in areas such as nutrition, exercise, stress management, sleep, and other lifestyle factors.',
     3069.17, 7),
    ('Occupational therapy', 'Occupational therapy (OT) is an allied health profession that involves the therapeutic use of everyday activities, or occupations, to treat the physical, mental, developmental, and emotional ailments that impact a patient''s ability to perform daily tasks.',
     409.22, 8),
    ('Speech therapy', 'Speech therapy can help people who have difficulty speaking to communicate better and to break down the barriers that result from speech impediments. The goals of speech therapy include improving pronunciation, strengthening the muscles used in speech, and learning to speak correctly.',
     920.75, 8),
    ('Cardiac rehabilitation', 'Cardiac rehabilitation (cardiac rehab) is a personalized program of education and exercise. The supervised program is designed to improve health in those with heart disease. It''s often recommended after a heart attack or heart surgery.',
     748.88, 8),
    ('Pain management', 'Pain management is an aspect of medicine and health care involving relief of pain (pain relief, analgesia, pain control) in various dimensions, from acute and simple to chronic and challenging.',
     544.27, 9),
    ('Hospice care', 'Hospice care focuses on the care, comfort, and quality of life of a person with a serious illness who is approaching the end of life. At some point, it may not be possible to cure a serious illness, or a patient may choose not to undergo certain treatments. Hospice is designed for this situation.',
     1329.98, 9),
    ('Cleaning', 'During a dental cleaning, a dentist or dental hygienist will remove bacteria, plaque and tartar buildup from your teeth surfaces. They may also perform other preventive services during the same visit, such as dental sealants and fluoride treatments. If you have dental fears or anxieties, talk to your dentist.',
     302.42, 10),
    ('Fillings and root canals', 'Root canal treatment is a method used in the treatment of deep tooth decay, painful, inflammatory, abscessed diseases in the teeth. Filling is a method used to repair the cavities that couldn''t reach to decays or directly the decays in teeth. Filling is a shorter procedure than root canal treatment.',
     690.00, 10),
    ('Orthodontic treatment', 'Orthodontics is a dental specialty focused on aligning your bite and straightening your teeth. You might need to see an orthodontist if you have crooked, overlapped, twisted or gapped teeth. Common orthodontic treatments include traditional braces, clear aligners and removable retainers.',
     20461.16, 10),
    ('Botox injections', 'Botox injections are shots that use a toxin to prevent a muscle from moving for a limited time. These shots are often used to smooth wrinkles on the face. They\'re also used to treat neck spasms, sweating, overactive bladder, lazy eye and other conditions.',
     1636.89, 11),
    ('Dermal fillers', 'Dermal fillers, also known as injectable implants, soft tissue fillers, lip and facial fillers, or wrinkle fillers are medical device implants approved by the FDA for use in helping to create a smoother and/or fuller appearance in the face, including nasolabial folds (the lines extending from the sides of the nose to the edges of the mouth), cheeks, chin, lips, and back of the hands.',
     2934.13, 11),
    ('Laser treatment', 'Laser treatment uses an intense, narrow beam of light to remove or destroy abnormal tissue. It is often used to treat precancers on the surface of the body, such as actinic keratosis, and may be used to treat some types of skin cancer.',
     140.00, 11),
    ('Chemical peels', 'A chemical peel is a procedure in which a chemical solution is applied to the skin to remove the top layers. The skin that grows back is smoother. With a light or medium peel, you may need to undergo the procedure more than once to get the desired results.',
     6093.33, 11),
    ('Cataract surgery', 'What happens during cataract surgery? During surgery, your eye doctor will remove the cloudy lens from your eye and replace it with an artificial lens (called an intraocular lens, or IOL). The surgery lasts about 1 hour and is almost painless.',
     16368.93, 12),
    ('LASIK', 'LASIK is eye surgery that permanently changes the shape of the cornea (the clear covering on the front of the eye). It is done to improve vision and reduce a person''s need for glasses or contact lenses.',
     5500.00, 12),
    ('Glaucoma treatment', 'Glaucoma treatment often starts with prescription eye drops. Some may decrease eye pressure by improving how fluid drains from your eye. Others decrease the amount of fluid your eye makes. Depending on how low your eye pressure needs to be, you may be prescribed more than one eye drop.',
     6138.35, 12);